# Generated by Django 5.2.9 on 2026-01-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
